const mockData = [
    { id: 1, location: 'Delhi', title: 'Meeting in Delhi', description: 'This is a meeting in Delhi.' },
    { id: 2, location: 'Delhi', title: 'Meeting in Delhi 2', description: 'This is a second meeting in Delhi.' },
    { id: 3, location: 'Delhi', title: 'Meeting in Delhi 3', description: 'This is a third meeting in Delhi.' },
    { id: 4, location: 'Delhi', title: 'Meeting in Delhi 4', description: 'This is a fourth meeting in Delhi.' },
    { id: 5, location: 'Delhi', title: 'Meeting in Delhi 5', description: 'This is a fifth meeting in Delhi.' },
    { id: 6, location: 'Delhi', title: 'Meeting in Delhi 6', description: 'This is a sixth meeting in Delhi.' },
    { id: 7, location: 'Delhi', title: 'Meeting in Delhi 7', description: 'This is a seventh meeting in Delhi.' },
    { id: 8, location: 'Delhi', title: 'Meeting in Delhi 8', description: 'This is an eighth meeting in Delhi.' },
    { id: 9, location: 'Delhi', title: 'Meeting in Delhi 9', description: 'This is a ninth meeting in Delhi.' },
    { id: 10, location: 'Delhi', title: 'Meeting in Delhi 10', description: 'This is a tenth meeting in Delhi.' },
    { id: 11, location: 'Mumbai', title: 'Meeting in Mumbai', description: 'This is a meeting in Mumbai.' },
    { id: 12, location: 'Mumbai', title: 'Meeting in Mumbai 2', description: 'This is a second meeting in Mumbai.' },
    { id: 13, location: 'Mumbai', title: 'Meeting in Mumbai 3', description: 'This is a third meeting in Mumbai.' },
    { id: 14, location: 'Mumbai', title: 'Meeting in Mumbai 4', description: 'This is a fourth meeting in Mumbai.' },
    { id: 15, location: 'Mumbai', title: 'Meeting in Mumbai 5', description: 'This is a fifth meeting in Mumbai.' },
    { id: 16, location: 'Mumbai', title: 'Meeting in Mumbai 6', description: 'This is a sixth meeting in Mumbai.' },
    { id: 17, location: 'Mumbai', title: 'Meeting in Mumbai 7', description: 'This is a seventh meeting in Mumbai.' },
    { id: 18, location: 'Mumbai', title: 'Meeting in Mumbai 8', description: 'This is an eighth meeting in Mumbai.' },
    { id: 19, location: 'Mumbai', title: 'Meeting in Mumbai 9', description: 'This is a ninth meeting in Mumbai.' },
    { id: 20, location: 'Mumbai', title: 'Meeting in Mumbai 10', description: 'This is a tenth meeting in Mumbai.' },
    { id: 21, location: 'Pune', title: 'Meeting in Pune', description: 'This is a meeting in Pune.' },
    { id: 22, location: 'Pune', title: 'Meeting in Pune 2', description: 'This is a second meeting in Pune.' },
    { id: 23, location: 'Pune', title: 'Meeting in Pune 3', description: 'This is a third meeting in Pune.' },
    { id: 24, location: 'Pune', title: 'Meeting in Pune 4', description: 'This is a fourth meeting in Pune.' },
    { id: 25, location: 'Pune', title: 'Meeting in Pune 5', description: 'This is a fifth meeting in Pune.' },
    { id: 26, location: 'Pune', title: 'Meeting in Pune 6', description: 'This is a sixth meeting in Pune.' },
    { id: 27, location: 'Pune', title: 'Meeting in Pune 7', description: 'This is a seventh meeting in Pune.' },
    { id: 28, location: 'Pune', title: 'Meeting in Pune 8', description: 'This is an eighth meeting in Pune.' },
    { id: 29, location: 'Pune', title: 'Meeting in Pune 9', description: 'This is a ninth meeting in Pune.' },
    { id: 30, location: 'Pune', title: 'Meeting in Pune 10', description: 'This is a tenth meeting in Pune.' },
    { id: 31, location: 'Chennai', title: 'Meeting in Chennai', description: 'This is a meeting in Chennai.' },
    { id: 32, location: 'Chennai', title: 'Meeting in Chennai 2', description: 'This is a second meeting in Chennai.' },
    { id: 33, location: 'Chennai', title: 'Meeting in Chennai 3', description: 'This is a third meeting in Chennai.' },
    { id: 34, location: 'Chennai', title: 'Meeting in Chennai 4', description: 'This is a fourth meeting in Chennai.' },
    { id: 35, location: 'Chennai', title: 'Meeting in Chennai 5', description: 'This is a fifth meeting in Chennai.' },
    { id: 36, location: 'Chennai', title: 'Meeting in Chennai 6', description: 'This is a sixth meeting in Chennai.' },
    { id: 37, location: 'Chennai', title: 'Meeting in Chennai 7', description: 'This is a seventh meeting in Chennai.' },
    { id: 38, location: 'Chennai', title: 'Meeting in Chennai 8', description: 'This is an eighth meeting in Chennai.' },
    { id: 39, location: 'Chennai', title: 'Meeting in Chennai 9', description: 'This is a ninth meeting in Chennai.' },
    { id: 40, location: 'Chennai', title: 'Meeting in Chennai 10', description: 'This is a tenth meeting in Chennai.' },
    { id: 41, location: 'Kolkata', title: 'Meeting in Kolkata', description: 'This is a meeting in Kolkata.' },
    { id: 42, location: 'Kolkata', title: 'Meeting in Kolkata 2', description: 'This is a second meeting in Kolkata.' },
    { id: 43, location: 'Kolkata', title: 'Meeting in Kolkata 3', description: 'This is a third meeting in Kolkata.' },
    { id: 44, location: 'Kolkata', title: 'Meeting in Kolkata 4', description: 'This is a fourth meeting in Kolkata.' },
    { id: 45, location: 'Kolkata', title: 'Meeting in Kolkata 5', description: 'This is a fifth meeting in Kolkata.' },
    { id: 46, location: 'Kolkata', title: 'Meeting in Kolkata 6', description: 'This is a sixth meeting in Kolkata.' },
    { id: 47, location: 'Kolkata', title: 'Meeting in Kolkata 7', description: 'This is a seventh meeting in Kolkata.' },
    { id: 48, location: 'Kolkata', title: 'Meeting in Kolkata 8', description: 'This is an eighth meeting in Kolkata.' },
    { id: 49, location: 'Kolkata', title: 'Meeting in Kolkata 9', description: 'This is a ninth meeting in Kolkata.' },
    { id: 50, location: 'Kolkata', title: 'Meeting in Kolkata 10', description: 'This is a tenth meeting in Kolkata.' },
  ];
  
const cityOptions = ['Delhi', 'Mumbai', 'Pune', 'Chennai', 'Kolkata'];
export { mockData, cityOptions };
